#!/bin/bash
echo "🎯 CRÉATION JOB JENKINS SIMPLIFIÉ"
echo "================================"

echo "📋 ÉTAPES EXACTES :"
echo ""
echo "1. 🌐 Ouvrez : http://localhost:8080"
echo "2. ➕ Cliquez : 'New Item'"
echo "3. 📝 Nom : 'devsecops-pipeline'"
echo "4. ✅ Type : 'Pipeline' → OK"
echo ""
echo "5. ⚙️ CONFIGURATION :"
echo "   - GitHub project : https://github.com/medchennouf/devsecops-project"
echo "   - Build Triggers : ✅ 'Poll SCM'"
echo "   - Schedule : '*/2 * * * *' (toutes les 2 minutes)"
echo ""
echo "6. 🚀 PIPELINE :"
echo "   - Definition : 'Pipeline script from SCM'"
echo "   - SCM : 'Git'"
echo "   - Repository : 'https://github.com/medchennouf/devsecops-project.git'"
echo "   - Branches : '*/main'"
echo "   - Script Path : 'Jenkinsfile-complet-devsecops'"
echo ""
echo "7. 💾 Sauvegardez"
echo ""
echo "🎉 APRÈS SAUVEGARDE :"
echo "   - Jenkins va IMMÉDIATEMENT détecter votre code"
echo "   - Le pipeline DevSecOps va s'exécuter !"
